###

POST http://localhost:5000/api/registration
Content-Type: application/json

{
    "email": "ekramullah70@gmail.com",
    "name": "Ekram Ullah",
    "password": "12345678"
}

###

POST http://localhost:5000/api/login
Content-Type: application/json

{
    "email": "ekramullah70@gmail.com",
    "password": "12345678"
}

###

GET  http://localhost:5000/api/getAllStories


###

GET  http://localhost:5000/api/stories/66cb3d17bd854eb845abe1ea

